[tool.poetry]
name = "fake-news-detector-2"
version = "0.1.0"
description = ""
authors = ["I.Roma"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
